/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package charging.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ChargingAppTest {
    @Test void appHasStarttime() {
        ChargingApp classUnderTest = new ChargingApp();
        assertNotNull(classUnderTest.startTime());
    }

    @Test void appHasEndtime() {
        ChargingApp classUnderTest = new ChargingApp();
        assertNotNull(classUnderTest.endTime());
    }

}
